package org.cancogenvirusseq.muse.api.model;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NonNull;

@Data
@Builder
@AllArgsConstructor
@ApiModel(description = "The Id generated by submitting the data processing in the Project")
public class ProjectStudyCreateResponse {
  @NonNull private String id;
}
